-- DECOLA MED — SEED: banco de flashcards FACAPE (lote enviado pelo usuário)
-- Gerado a partir de Flashcards_FACAPE_Medicina.md — 352 flashcards
-- Rodar no SQL editor do Supabase (ou via CLI) do projeto decolamed.

insert into flashcards (materia, assunto, frente, verso) values
  ('Biologia', 'Citologia', 'Membrana plasmática — composição básica', 'Bicamada fosfolipídica com proteínas periféricas e integrais dispostas em mosaico fluido (modelo do mosaico fluido de Singer e Nicolson).'),
  ('Biologia', 'Citologia', 'Função do colesterol na membrana plasmática', 'Regula a fluidez da membrana, diminuindo-a em altas temperaturas e evitando o congelamento em baixas temperaturas.'),
  ('Biologia', 'Citologia', 'Permeabilidade seletiva', 'Propriedade da membrana plasmática de controlar a entrada e saída de substâncias, mantendo a homeostase celular.'),
  ('Biologia', 'Citologia', 'Difusão simples', 'Movimento passivo de partículas do meio mais concentrado para o menos concentrado, sem gasto de energia, a favor do gradiente de concentração.'),
  ('Biologia', 'Citologia', 'Osmose', 'Difusão da água através de membrana semipermeável, do meio hipotônico para o hipertônico.'),
  ('Biologia', 'Citologia', 'Transporte ativo', 'Movimento de substâncias contra o gradiente de concentração, com gasto de energia (ATP), como na bomba de sódio e potássio.'),
  ('Biologia', 'Citologia', 'Endocitose', 'Processo de internalização de substâncias por invaginação da membrana plasmática; inclui fagocitose e pinocitose.'),
  ('Biologia', 'Citologia', 'Fagocitose', 'Englobamento de partículas sólidas (bactérias, restos celulares) por pseudópodes, comum em macrófagos e neutrófilos.'),
  ('Biologia', 'Citologia', 'Pinocitose', 'Englobamento de líquidos e substâncias dissolvidas através de pequenas invaginações da membrana.'),
  ('Biologia', 'Citologia', 'Exocitose', 'Processo de eliminação de substâncias do interior da célula por fusão de vesículas com a membrana plasmática.'),
  ('Biologia', 'Citologia', 'Retículo endoplasmático rugoso (granular)', 'Possui ribossomos aderidos; principal sítio de síntese de proteínas destinadas à secreção ou a membranas.'),
  ('Biologia', 'Citologia', 'Retículo endoplasmático liso', 'Sem ribossomos; sintetiza lipídios e esteroides, e participa da desintoxicação celular (ex.: hepatócitos).'),
  ('Biologia', 'Citologia', 'Complexo golgiense — função', 'Processa, empacota e distribui proteínas e lipídios vindos do retículo endoplasmático; forma lisossomos.'),
  ('Biologia', 'Citologia', 'Dictiossomas', 'Conjuntos de sacos membranosos achatados que compõem o complexo golgiense.'),
  ('Biologia', 'Citologia', 'Lisossomos — função', 'Organelas com enzimas hidrolíticas responsáveis pela digestão intracelular de macromoléculas e organelas velhas (autofagia).'),
  ('Biologia', 'Citologia', 'Mitocôndrias — função', 'Realizam a respiração celular aeróbica, convertendo energia química dos nutrientes em ATP.'),
  ('Biologia', 'Citologia', 'Origem evolutiva das mitocôndrias', 'Teoria endossimbiótica: mitocôndrias derivam de bactérias aeróbias que estabeleceram simbiose com células ancestrais; possuem DNA próprio.'),
  ('Biologia', 'Citologia', 'Ribossomos', 'Estruturas (livres ou aderidas ao RE) responsáveis pela síntese proteica, traduzindo o mRNA em cadeias polipeptídicas.'),
  ('Biologia', 'Citologia', 'Centríolos — função', 'Estruturas cilíndricas formadas por microtúbulos, essenciais na formação do fuso mitótico e na origem de cílios e flagelos.'),
  ('Biologia', 'Citologia', 'Célula eucariótica animal x vegetal', 'A vegetal possui parede celular, cloroplastos e vacúolo grande; a animal não possui essas estruturas, mas pode ter centríolos evidentes.'),
  ('Biologia', 'Citologia', 'Parede celular vegetal', 'Estrutura rígida externa à membrana plasmática, composta principalmente de celulose, que confere sustentação à célula vegetal.'),
  ('Biologia', 'Citologia', 'Célula procariótica x eucariótica', 'Procariótica não possui núcleo individualizado nem organelas membranosas; eucariótica possui núcleo com carioteca e organelas membranosas.'),
  ('Biologia', 'Citologia', 'Cromatina', 'Forma frouxa e descondensada do material genético (DNA + proteínas histonas) presente no núcleo interfásico.'),
  ('Biologia', 'Citologia', 'Eucromatina x heterocromatina', 'Eucromatina é menos condensada e transcricionalmente ativa; heterocromatina é mais condensada e geralmente inativa.'),
  ('Biologia', 'Citologia', 'Nucléolo', 'Região nuclear onde ocorre a síntese e montagem parcial dos ribossomos (rRNA).'),
  ('Biologia', 'Ciclo Celular', 'Fases do ciclo celular', 'Interfase (G1, S, G2) seguida da fase M (mitose ou meiose), que inclui a divisão do núcleo e do citoplasma.'),
  ('Biologia', 'Ciclo Celular', 'Fase G1', 'Período de crescimento celular e síntese de proteínas antes da replicação do DNA; não ocorre síntese de DNA.'),
  ('Biologia', 'Ciclo Celular', 'Fase S', 'Fase de síntese em que ocorre a duplicação (replicação) do DNA.'),
  ('Biologia', 'Ciclo Celular', 'Fase G2', 'Período após a duplicação do DNA, com síntese de proteínas necessárias à divisão celular; antecede a mitose.'),
  ('Biologia', 'Ciclo Celular', 'Prófase', 'Condensação dos cromossomos, desaparecimento do nucléolo e da carioteca, formação do fuso mitótico.'),
  ('Biologia', 'Ciclo Celular', 'Metáfase', 'Cromossomos condensados se alinham na placa equatorial da célula.'),
  ('Biologia', 'Ciclo Celular', 'Anáfase', 'Separação das cromátides-irmãs, que migram para polos opostos da célula.'),
  ('Biologia', 'Ciclo Celular', 'Telófase', 'Descondensação dos cromossomos, reconstituição da carioteca e do nucléolo; segue-se a citocinese.'),
  ('Biologia', 'Ciclo Celular', 'Mitose — finalidade biológica', 'Gera duas células-filhas geneticamente idênticas à célula-mãe (diploides), garantindo crescimento e reparo tecidual.'),
  ('Biologia', 'Ciclo Celular', 'Meiose — finalidade biológica', 'Produz células haploides geneticamente variáveis (gametas), reduzindo à metade o número de cromossomos.'),
  ('Biologia', 'Ciclo Celular', 'Crossing-over', 'Troca de segmentos entre cromátides homólogas na prófase I da meiose, aumentando a variabilidade genética.'),
  ('Biologia', 'Ciclo Celular', 'Quiasmas', 'Pontos de contato visíveis entre cromátides homólogas durante o crossing-over na prófase I.'),
  ('Biologia', 'Ciclo Celular', 'Sinapse (meiose)', 'Pareamento dos cromossomos homólogos durante a prófase I da meiose.'),
  ('Biologia', 'Ciclo Celular', 'Por que a divisão do citoplasma não ocorre na Prófase I', 'A citocinese (divisão do citoplasma) ocorre apenas ao final da telófase, não durante a prófase, que é a fase mais longa da Meiose I.'),
  ('Biologia', 'Genética', 'Estrutura do DNA', 'Dupla hélice de nucleotídeos, cada um formado por desoxirribose, grupo fosfato e base nitrogenada (A, T, C, G), unidos por pontes de hidrogênio entre bases complementares.'),
  ('Biologia', 'Genética', 'Pareamento de bases no DNA', 'Adenina com timina (2 pontes de hidrogênio) e citosina com guanina (3 pontes de hidrogênio).'),
  ('Biologia', 'Genética', 'Diferença entre DNA e RNA', 'RNA é fita simples, possui ribose (em vez de desoxirribose) e uracila no lugar da timina.'),
  ('Biologia', 'Genética', 'Transcrição', 'Processo de síntese de RNA mensageiro a partir de um molde de DNA, realizado pela RNA polimerase no núcleo.'),
  ('Biologia', 'Genética', 'Tradução', 'Processo de síntese proteica nos ribossomos, no qual o códon do mRNA é decodificado pelo anticódon do tRNA para incorporar aminoácidos.'),
  ('Biologia', 'Genética', 'Códon', 'Sequência de três nucleotídeos do mRNA que codifica um aminoácido específico.'),
  ('Biologia', 'Genética', 'Anticódon', 'Sequência complementar ao códon, localizada no tRNA, responsável pelo reconhecimento e pareamento com o mRNA.'),
  ('Biologia', 'Genética', 'Alelos', 'Formas alternativas de um mesmo gene, localizadas em loci correspondentes de cromossomos homólogos.'),
  ('Biologia', 'Genética', 'Genótipo x fenótipo', 'Genótipo é a constituição genética do indivíduo; fenótipo é a manifestação observável (morfológica, fisiológica) resultante da interação do genótipo com o ambiente.'),
  ('Biologia', 'Genética', 'Sistema sanguíneo ABO — alelos envolvidos', 'Três alelos (IA, IB, i) determinam os fenótipos A, B, AB e O; IA e IB são codominantes entre si e dominantes sobre i.'),
  ('Biologia', 'Genética', 'Genótipos do tipo sanguíneo AB', 'Apenas IAIB; apresenta os aglutinogênios A e B nas hemácias.'),
  ('Biologia', 'Genética', 'Genótipos do tipo sanguíneo O', 'Apenas ii; não apresenta aglutinogênios A nem B nas hemácias.'),
  ('Biologia', 'Genética', 'Aglutinogênios e aglutininas', 'Aglutinogênios são antígenos nas hemácias; aglutininas são anticorpos no plasma contra os aglutinogênios ausentes no próprio sangue.'),
  ('Biologia', 'Genética', 'Doador universal do sistema ABO', 'Tipo O, por não possuir aglutinogênios A ou B que provoquem reação em outros tipos.'),
  ('Biologia', 'Genética', 'Herança ligada ao sexo — hemofilia', 'Doença recessiva ligada ao cromossomo X; homens hemizigotos (um só alelo) manifestam a doença com apenas um alelo recessivo.'),
  ('Biologia', 'Genética', 'Mulher portadora de hemofilia', 'Mulher heterozigota (XHXh) que não manifesta a doença, mas pode transmitir o alelo recessivo à prole.'),
  ('Biologia', 'Genética', 'Por que a hemofilia é mais comum em homens', 'Homens possuem apenas um cromossomo X; basta um alelo recessivo para manifestar a doença, enquanto mulheres precisam de dois alelos recessivos (homozigose).'),
  ('Biologia', 'Genética', 'Mutação cromossômica numérica', 'Alteração no número total de cromossomos (ex.: aneuploidias, como trissomias), podendo causar fenótipo anormal ou letalidade.'),
  ('Biologia', 'Genética', 'Síntese Moderna da Evolução (Neodarwinismo)', 'Integra a teoria da seleção natural de Darwin com a genética mendeliana, explicando a evolução como mudança nas frequências alélicas das populações ao longo do tempo.'),
  ('Biologia', 'Genética', 'Adaptação (conceito evolutivo)', 'Resultado do acúmulo de variações favoráveis selecionadas ao longo de gerações, tornando o organismo mais apto ao seu ambiente.'),
  ('Biologia', 'Fisiologia Humana', 'Hematócrito', 'Percentual do volume sanguíneo total ocupado pelos eritrócitos (hemácias), obtido por centrifugação do sangue.'),
  ('Biologia', 'Fisiologia Humana', 'Camadas do sangue centrifugado', 'Plasma (sobrenadante, ~55%), leucócitos e plaquetas (camada leucocitária, ~1%) e eritrócitos (camada inferior, 35-50%).'),
  ('Biologia', 'Fisiologia Humana', 'Função dos eritrócitos', 'Transporte de gases respiratórios (O2 e CO2) através da hemoglobina.'),
  ('Biologia', 'Fisiologia Humana', 'Função dos leucócitos', 'Defesa do organismo contra agentes patogênicos, atuando na resposta imune.'),
  ('Biologia', 'Fisiologia Humana', 'Função das plaquetas (trombócitos)', 'Participação no processo de coagulação sanguínea.'),
  ('Biologia', 'Fisiologia Humana', 'Origem das células sanguíneas', 'Todas são produzidas na medula óssea vermelha a partir de células-tronco hematopoiéticas.'),
  ('Biologia', 'Fisiologia Humana', 'Válvula mitral (bicúspide)', 'Localizada entre átrio esquerdo e ventrículo esquerdo; impede o refluxo de sangue oxigenado para o átrio.'),
  ('Biologia', 'Fisiologia Humana', 'Válvula tricúspide', 'Localizada entre átrio direito e ventrículo direito.'),
  ('Biologia', 'Fisiologia Humana', 'Diapedese', 'Processo pelo qual os leucócitos atravessam a parede dos capilares sanguíneos para atuar nos tecidos.'),
  ('Biologia', 'Fisiologia Humana', 'Órgãos do tubo digestório', 'Boca, faringe, esôfago, estômago, intestino delgado e intestino grosso.'),
  ('Biologia', 'Fisiologia Humana', 'Glândulas anexas do sistema digestório', 'Glândulas salivares, fígado e pâncreas.'),
  ('Biologia', 'Fisiologia Humana', 'Digestão de carboidratos na boca', 'A amilase salivar (ptialina) inicia a quebra do amido em moléculas menores.'),
  ('Biologia', 'Fisiologia Humana', 'Deglutição', 'Passagem do bolo alimentar da boca para o esôfago através de movimentos peristálticos, coordenados pela faringe.'),
  ('Biologia', 'Fisiologia Humana', 'Principal local de digestão de moléculas complexas', 'Intestino delgado (especialmente duodeno), onde atuam enzimas pancreáticas e a bile.'),
  ('Biologia', 'Fisiologia Humana', 'Absorção de água no intestino grosso', 'Torna o conteúdo luminal semissólido, formando as fezes.'),
  ('Biologia', 'Fisiologia Humana', 'Função da bile', 'Emulsificar as gorduras, facilitando a ação das lipases no intestino delgado; produzida no fígado e armazenada na vesícula biliar.'),
  ('Biologia', 'Fisiologia Humana', 'Absorção de carboidratos', 'São absorvidos na forma de monossacarídeos (como glicose) no intestino delgado.'),
  ('Biologia', 'Fisiologia Humana', 'Neurônio — função', 'Célula especializada na recepção, condução e transmissão de impulsos nervosos.'),
  ('Biologia', 'Fisiologia Humana', 'Partes do neurônio', 'Corpo celular (soma), dendritos (recebem estímulos) e axônio (conduz o impulso).'),
  ('Biologia', 'Fisiologia Humana', 'Sinapse', 'Região de comunicação entre neurônios (ou entre neurônio e célula efetora), onde ocorre a liberação de neurotransmissores, com transmissão unidirecional do axônio para a outra célula.'),
  ('Biologia', 'Fisiologia Humana', 'Células da glia (neuróglia)', 'Células de suporte, nutrição e proteção do tecido nervoso, além dos neurônios propriamente ditos.'),
  ('Biologia', 'Fisiologia Humana', 'Fermentação lática — quando ocorre no músculo', 'Em condição de baixa disponibilidade de oxigênio, as células musculares produzem energia por metabolismo anaeróbio, gerando ácido lático como subproduto.'),
  ('Biologia', 'Fisiologia Humana', 'Ácido lático e fadiga muscular', 'O acúmulo de ácido lático reduz a capacidade contrátil do músculo, provocando fadiga e cãibras.'),
  ('Biologia', 'Fisiologia Humana', 'Serotonina — papel fisiológico', 'Neurotransmissor associado à regulação do humor e do bem-estar; sua redução na sinapse está associada a sintomas depressivos.'),
  ('Biologia', 'Fisiologia Humana', 'BDNF (fator neurotrófico derivado do cérebro)', 'Proteína liberada durante exercício aeróbico que estimula a neurogênese e a função cognitiva.'),
  ('Biologia', 'Ecologia', 'Hierarquia ecológica (do menor para o maior nível)', 'Organismo → população → comunidade (biocenose) → ecossistema → bioma → biosfera.'),
  ('Biologia', 'Ecologia', 'População (ecologia)', 'Conjunto de organismos da mesma espécie que coexistem em determinada área e período, formando uma unidade reprodutiva.'),
  ('Biologia', 'Ecologia', 'Comunidade (biocenose)', 'Conjunto de populações de diferentes espécies que interagem em uma mesma área.'),
  ('Biologia', 'Ecologia', 'Ecossistema', 'Conjunto formado pela comunidade biológica (fatores bióticos) e o ambiente físico (fatores abióticos) com os quais interage.'),
  ('Biologia', 'Ecologia', 'Nicho ecológico', 'Conjunto de funções e relações que uma espécie desempenha dentro do seu habitat (alimentação, reprodução, interações).'),
  ('Biologia', 'Ecologia', 'Habitat x nicho ecológico', 'Habitat é o "endereço" físico onde a espécie vive; nicho é a "profissão", o papel funcional que ela exerce no ecossistema.'),
  ('Biologia', 'Ecologia', 'Teia alimentar', 'Conjunto de cadeias alimentares interligadas em um mesmo ecossistema, considerando que uma espécie pode ocupar diferentes níveis tróficos.'),
  ('Biologia', 'Ecologia', 'Competição (relação ecológica)', 'Disputa entre indivíduos da mesma espécie ou de espécies diferentes por recursos limitados do ambiente.'),
  ('Biologia', 'Ecologia', 'Mutualismo', 'Relação harmônica interespecífica em que ambas as espécies obtêm benefícios.'),
  ('Biologia', 'Ecologia', 'Amensalismo (antibiose)', 'Relação em que uma espécie libera substâncias que inibem o crescimento ou desenvolvimento de outra, sem benefício direto para quem libera.'),
  ('Biologia', 'Ecologia', 'Protocooperação', 'Relação harmônica interespecífica facultativa em que ambas as espécies se beneficiam, mas podem sobreviver isoladamente.'),
  ('Biologia', 'Ecologia', 'Comensalismo', 'Relação em que uma espécie se beneficia e a outra não é beneficiada nem prejudicada.'),
  ('Biologia', 'Ecologia', 'Bioma Caatinga — características climáticas', 'Clima semiárido, quente, com chuvas escassas e irregulares concentradas em curto período do ano (menos de 1.000 mm anuais).'),
  ('Biologia', 'Ecologia', 'Caducifolia na Caatinga', 'Perda das folhas na estação seca como adaptação para reduzir a perda de água por transpiração.'),
  ('Biologia', 'Ecologia', 'Exclusividade da Caatinga', 'É o único bioma exclusivamente brasileiro.'),
  ('Biologia', 'Ecologia', 'Espécies vegetais nativas da Caatinga', 'Mandacaru, xique-xique, palma (nativa), caatingueira verdadeira; algaroba e mulungu não são nativos (algaroba é espécie introduzida/exótica).'),
  ('Biologia', 'Ecologia', 'Espécie exótica invasora — impacto ecológico', 'Pode competir com espécies nativas por recursos, alterar ciclos naturais do ecossistema e reduzir a biodiversidade local.'),
  ('Biologia', 'Ecologia', 'Ciclos biogeoquímicos', 'Movimento contínuo de elementos químicos essenciais (carbono, nitrogênio, água etc.) entre componentes bióticos e abióticos do ecossistema.'),
  ('Biologia', 'Ecologia', 'Efeito estufa — consequência do excesso de gases', 'Retenção excessiva de calor na atmosfera, provocando aquecimento global e desequilíbrios climáticos.'),
  ('Biologia', 'Ecologia', 'Consequência do aquecimento global nos oceanos', 'Elevação do nível do mar por expansão térmica da água e derretimento das calotas polares.'),
  ('Biologia', 'Botânica', 'Estômatos', 'Estruturas epidérmicas responsáveis pelas trocas gasosas e pela transpiração vegetal.'),
  ('Biologia', 'Botânica', 'Cloroplastos — função', 'Organelas onde ocorre a fotossíntese, produzindo glicose e oxigênio a partir de luz, água e CO2.'),
  ('Biologia', 'Botânica', 'Xilema (vaso lenhoso)', 'Tecido condutor formado por células mortas, responsável pelo transporte de seiva bruta (água e sais minerais) das raízes às folhas.'),
  ('Biologia', 'Botânica', 'Floema (vaso liberiano)', 'Tecido condutor formado por células vivas, responsável pelo transporte de seiva elaborada (açúcares) das folhas para as demais partes da planta.'),
  ('Biologia', 'Botânica', 'Cutícula vegetal', 'Camada cerosa que reveste a epiderme e reduz a perda excessiva de água por transpiração.'),
  ('Biologia', 'Botânica', 'Parênquima clorofiliano', 'Tecido formado por células vivas responsáveis pela fotossíntese e pelo armazenamento de substâncias.'),
  ('Biologia', 'Botânica', 'Esclerênquima', 'Tecido de sustentação formado por células mortas com paredes espessadas por lignina (fibras e esclereides).'),
  ('Química', 'Ligações Químicas', 'Ligação iônica', 'Formada pela transferência de elétrons entre átomos com grande diferença de eletronegatividade, geralmente entre metal e não metal.'),
  ('Química', 'Ligações Químicas', 'Ligação covalente', 'Formada pelo compartilhamento de pares de elétrons entre átomos, geralmente entre não metais.'),
  ('Química', 'Ligações Químicas', 'Ligação covalente do tipo sigma (σ)', 'Formada pela sobreposição frontal de orbitais, permitindo livre rotação entre os átomos ligados.'),
  ('Química', 'Ligações Químicas', 'Isótopos', 'Átomos do mesmo elemento químico (mesmo número atômico Z) que diferem no número de massa (A), possuindo número diferente de nêutrons.'),
  ('Química', 'Ligações Químicas', 'Isômeros nucleares', 'Núcleos com o mesmo número de prótons e nêutrons, mas em diferentes estados de energia (ex.: 99mTc e 99Tc).'),
  ('Química', 'Funções Orgânicas', 'Função álcool', 'Composto orgânico que apresenta grupo hidroxila (–OH) ligado a carbono saturado.'),
  ('Química', 'Funções Orgânicas', 'Álcool secundário', 'Grupo hidroxila ligado a um carbono que está ligado a outros dois átomos de carbono.'),
  ('Química', 'Funções Orgânicas', 'Regra de Saytzeff (Zaitsev)', 'Na desidratação intramolecular de álcoois, o produto majoritário é o alceno mais substituído (mais estável).'),
  ('Química', 'Funções Orgânicas', 'Reação de eliminação', 'Reação em que um átomo/grupo é retirado da molécula, formando uma insaturação (ex.: desidratação de álcoois para formar alcenos).'),
  ('Química', 'Funções Orgânicas', 'Função ácido carboxílico', 'Composto orgânico caracterizado pelo grupo carboxila (–COOH).'),
  ('Química', 'Funções Orgânicas', 'Reação de esterificação', 'Reação entre um ácido carboxílico e um álcool, produzindo éster e água.'),
  ('Química', 'Funções Orgânicas', 'Isomeria de função', 'Compostos com mesma fórmula molecular, mas pertencentes a funções orgânicas diferentes (ex.: álcool e éter).'),
  ('Química', 'Funções Orgânicas', 'Isomeria de cadeia', 'Compostos com mesma fórmula molecular, mas com esqueleto de carbono estruturalmente diferente (normal, ramificado, cíclico).'),
  ('Química', 'Funções Orgânicas', 'Carbono quiral (assimétrico)', 'Átomo de carbono ligado a quatro grupos (substituintes) diferentes entre si, responsável pela atividade óptica das moléculas.'),
  ('Química', 'Funções Orgânicas', 'Enantiômeros', 'Isômeros ópticos que são imagens especulares não sobreponíveis um do outro.'),
  ('Química', 'Funções Orgânicas', 'Carboidratos — grupo funcional predominante na glicose', 'A glicose (aldose) apresenta grupo aldeído e múltiplas hidroxilas (poliálcool-aldeído).'),
  ('Química', 'Estequiometria', 'Mol', 'Unidade que representa 6,02 × 10²³ entidades elementares (constante de Avogadro), correspondendo à massa molar em gramas de uma substância.'),
  ('Química', 'Estequiometria', 'Volume molar nas CNTP', 'Um mol de qualquer gás ideal ocupa aproximadamente 22,4 L nas Condições Normais de Temperatura e Pressão (0 °C, 1 atm).'),
  ('Química', 'Estequiometria', 'Equação de Clapeyron (gases ideais)', 'PV = nRT, relaciona pressão, volume, número de mols, constante universal dos gases e temperatura absoluta.'),
  ('Química', 'Estequiometria', 'Concentração molar (mol/L)', 'Razão entre a quantidade de matéria (mol) do soluto e o volume da solução em litros.'),
  ('Química', 'Estequiometria', 'Reagente limitante', 'Reagente que é totalmente consumido primeiro na reação, determinando a quantidade máxima de produto formado.'),
  ('Química', 'Termoquímica', 'Reação exotérmica', 'Libera energia (calor) para o ambiente; a entalpia dos produtos é menor que a dos reagentes (ΔH negativo).'),
  ('Química', 'Termoquímica', 'Reação endotérmica', 'Absorve energia (calor) do ambiente; a entalpia dos produtos é maior que a dos reagentes (ΔH positivo).'),
  ('Química', 'Termoquímica', 'Entalpia (ΔH)', 'Variação de energia térmica associada a uma transformação química, medida a pressão constante.'),
  ('Química', 'Termoquímica', 'Calor específico', 'Quantidade de energia necessária para elevar em 1 °C a temperatura de 1 grama de uma substância.'),
  ('Química', 'Equilíbrio Químico', 'Princípio de Le Chatelier', 'Quando um sistema em equilíbrio sofre uma perturbação (concentração, pressão, temperatura), ele se desloca no sentido de minimizar essa perturbação.'),
  ('Química', 'Equilíbrio Químico', 'Constante de ionização (Ka)', 'Mede a força de um ácido; quanto maior o Ka, mais forte (mais ionizado) é o ácido.'),
  ('Química', 'Equilíbrio Químico', 'Sistema tampão bicarbonato', 'Sistema HCO3⁻/H2CO3 que regula o pH sanguíneo, neutralizando excessos de ácidos ou bases no plasma.'),
  ('Química', 'Eletroquímica', 'Pilha (célula galvânica)', 'Dispositivo que converte energia química em energia elétrica através de reações de oxirredução espontâneas.'),
  ('Química', 'Eletroquímica', 'Ânodo x cátodo (pilha)', 'Ânodo é o eletrodo onde ocorre oxidação (perda de elétrons); cátodo é onde ocorre redução (ganho de elétrons).'),
  ('Química', 'Eletroquímica', 'Eletrólise', 'Processo não espontâneo em que a energia elétrica é utilizada para provocar reações de oxirredução.'),
  ('Química', 'Radioatividade', 'Meia-vida', 'Tempo necessário para que a quantidade de um material radioativo se reduza à metade do valor inicial.'),
  ('Química', 'Radioatividade', 'Emissão alfa', 'Emissão de partícula composta por 2 prótons e 2 nêutrons; reduz o número atômico em 2 e o número de massa em 4.'),
  ('Química', 'Radioatividade', 'Emissão beta', 'Emissão de elétron originado da conversão de um nêutron em próton no núcleo; aumenta o número atômico em 1, mantendo o número de massa.'),
  ('Química', 'Radioatividade', 'Emissão gama', 'Emissão de radiação eletromagnética de alta energia, sem alteração no número atômico ou de massa, geralmente após emissões alfa ou beta.'),
  ('Física', 'Cinemática', 'Movimento Retilíneo Uniformemente Variado (MRUV) — equação de Torricelli', 'v² = v0² + 2·a·Δs, relaciona velocidade final, velocidade inicial, aceleração e deslocamento, sem depender do tempo.'),
  ('Física', 'Cinemática', 'Queda livre', 'Movimento uniformemente acelerado sob ação exclusiva da gravidade, com velocidade inicial nula (quando abandonado do repouso).'),
  ('Física', 'Cinemática', 'Aceleração da gravidade — determinação experimental', 'Pode ser obtida a partir da relação entre distância percorrida em queda livre e o tempo decorrido, usando s = g·t²/2.'),
  ('Física', 'Dinâmica', 'Segunda Lei de Newton', 'A força resultante sobre um corpo é igual ao produto de sua massa pela aceleração adquirida (F = m·a).'),
  ('Física', 'Dinâmica', 'Força de atrito estático máximo', 'Fat = μe · N, onde μe é o coeficiente de atrito estático e N é a força normal.'),
  ('Física', 'Dinâmica', 'Empuxo (Princípio de Arquimedes)', 'Força vertical para cima exercida por um fluido sobre um corpo nele imerso, igual ao peso do volume de fluido deslocado.'),
  ('Física', 'Dinâmica', 'Conservação da quantidade de movimento (colisões)', 'Em um sistema isolado, a quantidade de movimento total antes da colisão é igual à quantidade de movimento total depois da colisão.'),
  ('Física', 'Dinâmica', 'Energia potencial elástica', 'Ep = k·x²/2, energia armazenada em uma mola deformada, onde k é a constante elástica e x é a deformação.'),
  ('Física', 'Termologia', 'Calor sensível — fórmula', 'Q = m·c·ΔT, onde m é a massa, c o calor específico e ΔT a variação de temperatura.'),
  ('Física', 'Termologia', 'Calor latente — fórmula', 'Q = m·L, energia envolvida em uma mudança de estado físico sem variação de temperatura, onde L é o calor latente específico.'),
  ('Física', 'Termologia', 'Princípio das trocas de calor (calorimetria)', 'Em um sistema termicamente isolado, a soma algébrica dos calores trocados entre os corpos é igual a zero (Qcedido + Qrecebido = 0).'),
  ('Física', 'Termologia', 'Dilatação térmica linear', 'ΔL = L0·α·ΔT, onde α é o coeficiente de dilatação linear do material.'),
  ('Física', 'Termologia', 'Efeito Doppler (som)', 'Alteração aparente da frequência percebida de uma onda sonora devido ao movimento relativo entre fonte e observador.'),
  ('Física', 'Óptica', 'Lei de Snell (refração)', 'n1·sen(θ1) = n2·sen(θ2), relaciona os índices de refração e os ângulos de incidência e refração entre dois meios.'),
  ('Física', 'Óptica', 'Ângulo limite e reflexão total', 'Ângulo de incidência a partir do qual toda a luz é refletida internamente, ocorrendo quando a luz passa de meio mais refringente para menos refringente.'),
  ('Física', 'Óptica', 'Equação de Gauss (lentes/espelhos)', '1/f = 1/p + 1/p'', relaciona distância focal, distância do objeto e distância da imagem.'),
  ('Física', 'Óptica', 'Aumento linear transversal', 'A = -p''/p = i/o, razão entre o tamanho da imagem e o tamanho do objeto.'),
  ('Física', 'Óptica', 'Hipermetropia — correção óptica', 'Corrigida com lentes convergentes, que aproximam o ponto de convergência da imagem para dentro do olho.'),
  ('Física', 'Eletricidade', 'Lei de Ohm', 'U = R·i, relaciona tensão elétrica, resistência e corrente elétrica em um resistor ôhmico.'),
  ('Física', 'Eletricidade', 'Associação de resistores em série', 'A resistência equivalente é a soma das resistências individuais (Req = R1 + R2 + ...); a corrente é a mesma em todos os resistores.'),
  ('Física', 'Eletricidade', 'Associação de resistores em paralelo', 'O inverso da resistência equivalente é a soma dos inversos das resistências (1/Req = 1/R1 + 1/R2 + ...); a tensão é a mesma em todos os resistores.'),
  ('Física', 'Eletricidade', 'Capacitor — carga armazenada', 'Q = C·U, onde C é a capacitância e U é a tensão aplicada.'),
  ('Física', 'Eletricidade', 'Energia armazenada em capacitor', 'E = C·U²/2, energia potencial elétrica armazenada no campo elétrico do capacitor.'),
  ('Física', 'Eletricidade', 'Lei de Coulomb', 'F = k·|q1·q2|/d², descreve a força elétrica entre duas cargas puntiformes, proporcional ao produto das cargas e inversamente proporcional ao quadrado da distância.'),
  ('Matemática', 'Progressão Aritmética', 'Termo geral da PA', 'an = a1 + (n-1)·r, onde a1 é o primeiro termo e r é a razão da progressão.'),
  ('Matemática', 'Progressão Aritmética', 'Soma dos termos de uma PA finita', 'Sn = (a1 + an)·n/2.'),
  ('Matemática', 'Progressão Geométrica', 'Termo geral da PG', 'an = a1·q^(n-1), onde q é a razão da progressão geométrica.'),
  ('Matemática', 'Progressão Geométrica', 'Soma dos termos de uma PG finita', 'Sn = a1·(q^n - 1)/(q - 1), para q ≠ 1.'),
  ('Matemática', 'Matemática Financeira', 'Juros compostos — fórmula do montante', 'M = C·(1+i)^t, onde C é o capital inicial, i é a taxa de juros e t é o tempo.'),
  ('Matemática', 'Porcentagem', 'Aumentos sucessivos — cálculo', 'Cada aumento percentual multiplica sucessivamente o valor por (1 + taxa/100), sem simplesmente somar as porcentagens.'),
  ('Matemática', 'Análise Combinatória', 'Combinação simples — fórmula', 'Cn,p = n!/[p!·(n-p)!], usada quando a ordem dos elementos escolhidos não importa.'),
  ('Matemática', 'Probabilidade', 'Probabilidade — definição clássica', 'Razão entre o número de casos favoráveis e o número total de casos possíveis (equiprováveis).'),
  ('Matemática', 'Geometria Plana', 'Área do círculo', 'A = π·r², onde r é o raio da circunferência.'),
  ('Matemática', 'Geometria Espacial', 'Volume da esfera', 'V = (4/3)·π·r³.'),
  ('Matemática', 'Geometria Espacial', 'Volume do cilindro', 'V = π·r²·h, onde r é o raio da base e h é a altura.'),
  ('Matemática', 'Função Quadrática', 'Vértice da parábola (função quadrática)', 'Coordenadas dadas por xv = -b/2a e yv = -Δ/4a; representa o ponto de máximo ou mínimo da função.'),
  ('Português', 'Coesão Textual', 'Coesivo "porém"', 'Conjunção adversativa que introduz ideia de contraste ou oposição entre orações.'),
  ('Português', 'Coesão Textual', 'Coesivo "para que" / "a fim de"', 'Expressam relação semântica de finalidade entre as orações.'),
  ('Português', 'Coesão Textual', 'Coesivo "já que" / "uma vez que"', 'Expressam relação semântica de causa.'),
  ('Português', 'Coesão Textual', 'Coesivo "embora" / "apesar de"', 'Expressam relação semântica de concessão.'),
  ('Português', 'Coesão Textual', 'Anáfora', 'Recurso coesivo que retoma um termo ou ideia mencionada anteriormente no texto.'),
  ('Português', 'Sintaxe', 'Adjunto adverbial de finalidade', 'Termo/oração que indica o objetivo de uma ação (ex.: "para recuperar os músculos...").'),
  ('Português', 'Sintaxe', 'Complemento nominal x adjunto adnominal', 'Complemento nominal completa sentido de nome abstrato e é sempre preposicionado com sentido passivo; adjunto adnominal caracteriza o nome sem exigência de regência.'),
  ('Português', 'Sintaxe', 'Regência nominal', 'Relação de dependência entre um nome e seu complemento, geralmente exigindo preposição específica.'),
  ('Português', 'Morfologia', 'Pronome possessivo substantivado', 'Pronome possessivo que funciona como núcleo (substituindo o substantivo), como em "Mine is black" (o meu é preto).'),
  ('Português', 'Funções da Linguagem', 'Função conativa (apelativa)', 'Centrada no receptor, busca convencê-lo ou influenciá-lo a agir de determinada forma (própria de textos publicitários e campanhas).'),
  ('Português', 'Funções da Linguagem', 'Função referencial', 'Centrada no contexto/referente, tem como objetivo informar de maneira objetiva.'),
  ('Português', 'Funções da Linguagem', 'Função emotiva', 'Centrada no emissor, expressa sentimentos, opiniões e estados emocionais.'),
  ('Literatura', 'Grande Sertão: Veredas', 'Autor de Grande Sertão: Veredas', 'João Guimarães Rosa.'),
  ('Literatura', 'Grande Sertão: Veredas', 'Narrador de Grande Sertão: Veredas', 'Riobaldo, ex-jagunço, narra em primeira pessoa suas vivências em um longo monólogo a um doutor da cidade.'),
  ('Literatura', 'Grande Sertão: Veredas', 'Tema central de Grande Sertão: Veredas', 'O jaguncismo no sertão brasileiro, entrelaçando amor, guerra, violência estrutural e desigualdade social.'),
  ('Literatura', 'A Moreninha', 'Autor de A Moreninha', 'Joaquim Manuel de Macedo.'),
  ('Literatura', 'A Moreninha', 'Características de A Moreninha', 'Romance romântico marcado pelo amor idealizado, nacionalismo e exploração das relações sociais da época, ambientado no Rio de Janeiro.'),
  ('Literatura', 'Terras do Sem-Fim', 'Autor de Terras do Sem-Fim', 'Jorge Amado.'),
  ('Literatura', 'Terras do Sem-Fim', 'Cenário de Terras do Sem-Fim', 'Os grandes latifúndios e o ciclo do cacau na região de Ilhéus, sul da Bahia, retratando os coronéis da região.'),
  ('Literatura', 'Os Homens de Barro', 'Autor de Os Homens de Barro', 'Ariano Suassuna.'),
  ('Literatura', 'Os Homens de Barro', 'Temática de Os Homens de Barro', 'Resistência do sertanejo contra a opressão dos fazendeiros, com destaque para a seca, o misticismo e a desigualdade social no sertão paraibano/pernambucano.'),
  ('Literatura', 'O Quinze', 'Autora de O Quinze', 'Rachel de Queiroz.'),
  ('Literatura', 'O Quinze', 'Tema de O Quinze', 'A seca de 1915 no Ceará e o êxodo de famílias retirantes, com linguagem simples, natural e espontânea.'),
  ('Literatura', 'Memórias de um Sargento de Milícias', 'Autor de Memórias de um Sargento de Milícias', 'Manuel Antônio de Almeida.'),
  ('Literatura', 'Memórias de um Sargento de Milícias', 'Estilo de Memórias de um Sargento de Milícias', 'Romance que retrata, com humor, a vida de malandros das classes populares no Rio de Janeiro do início do século XIX, ironizando costumes da sociedade.'),
  ('Inglês', 'Voz Passiva', 'Estrutura da voz passiva no presente', 'Sujeito + to be (is/are) + particípio passado + (by + agente da passiva).'),
  ('Inglês', 'Condicionais', 'Third conditional — estrutura', 'If + past perfect, would have + past participle (ex.: "If I had seen the accident, I would have called the ambulance").'),
  ('Inglês', 'Verbos Modais', 'Futuro simples com verbo modal "can"', 'Substituição de "can" por "will be able to" para formar o futuro (ex.: "Will you be able to drive?").'),
  ('Inglês', 'Discurso Indireto', 'Reported speech — mudança verbal', 'O verbo da fala original recua um tempo verbal (ex.: "had been" no lugar de "was") ao ser reportado.'),
  ('Inglês', 'Classes Gramaticais', 'Numerais ordinais em inglês', 'Palavras como "tenth, first, third, fourth" indicam ordem/posição, classificando-se como numerais.'),
  ('Espanhol', 'Pronomes', 'Pronome "se" com função de impessoalidade', 'Usado para indicar sujeito indeterminado, sem agente específico definido na oração.'),
  ('Espanhol', 'Pronomes', 'Substituição de complemento indireto + direto ("se lo/la")', 'Quando "le/les" (complemento indireto) antecede "lo/la/los/las" (complemento direto), "le/les" transforma-se em "se".'),
  ('Espanhol', 'Tempos Verbais', 'Pretérito imperfecto — uso', 'Indica ações habituais ou contínuas no passado (ex.: "Cuando era niño, jugaba en el parque todos los días").'),
  ('Espanhol', 'Conectores', '"Sin embargo"', 'Conector de oposição, equivalente a "no entanto"; pode ser substituído por "a pesar de eso" sem alterar o sentido.'),
  ('História', 'Era Vargas', 'Política dos Governadores (Campos Sales)', 'Sistema de barganha política entre o governo federal e as oligarquias estaduais durante a República Velha, garantindo apoio mútuo.'),
  ('História', 'Era Vargas', 'Legislação trabalhista de Vargas', 'Instituiu jornada de 8 horas, salário-mínimo, férias remuneradas e direito à organização sindical, consolidados na CLT.'),
  ('História', 'Revolução Francesa e Iluminismo', 'Ideais centrais do Iluminismo', 'Uso da razão e da ciência para alcançar progresso e liberdade, com postura crítica ao absolutismo e à Igreja.'),
  ('História', 'Guerra Fria', 'Características da Guerra Fria', 'Divisão do mundo em blocos ideológicos liderados por EUA (capitalismo) e URSS (socialismo), com disputas indiretas em territórios periféricos.'),
  ('História', 'Idade Média', 'Papel da Igreja Católica na Idade Média', 'Exercia grande influência sobre a vida política, social e cultural, sendo centro de poder ao lado da nobreza feudal.'),
  ('História', 'Brasil República', 'Tenentismo', 'Movimento de contestação política liderado por militares de baixa patente (tenentes), crítico às oligarquias da República Velha.'),
  ('História', 'Segunda Guerra Mundial', 'Tríplice Entente x Tríplice Aliança (Primeira Guerra)', 'Entente: França, Império Britânico e Império Russo; Aliança: Império Alemão, Áustro-Húngaro e Turco-Otomano.'),
  ('Geografia', 'Geomorfologia', 'Intemperismo físico (mecânico)', 'Desintegração da rocha por variações de temperatura ou infiltração de água, sem alteração da composição química do material.'),
  ('Geografia', 'Geomorfologia', 'Intemperismo químico', 'Alteração da composição química dos minerais das rochas por reação com água, ar ou seres vivos.'),
  ('Geografia', 'Climatologia', 'Pressão atmosférica e altitude', 'Quanto maior a altitude, menor a coluna de ar sobre a superfície e, portanto, menor a pressão atmosférica.'),
  ('Geografia', 'Geologia', 'Rochas magmáticas intrusivas (plutônicas)', 'Formam-se pelo resfriamento lento do magma no interior da crosta, permitindo a formação de cristais grandes (ex.: diorito, granito).'),
  ('Geografia', 'Geologia', 'Rochas magmáticas extrusivas (vulcânicas)', 'Formam-se pelo resfriamento rápido do magma na superfície, resultando em cristais pequenos ou ausência deles (ex.: basalto, obsidiana).'),
  ('Geografia', 'Geografia Urbana', 'Segregação socioespacial urbana', 'Processo de desigualdade na distribuição do espaço urbano, associado à exclusão de populações vulneráveis das áreas centrais e valorizadas.'),
  ('Geografia', 'Geopolítica', 'Zona de Convergência Intertropical (ZCIT)', 'Sistema atmosférico que controla os períodos de chuva na faixa tropical, influenciando a sazonalidade climática na Mesoamérica e norte da América do Sul.'),
  ('Biologia', 'Fisiologia Humana — Respiratório', 'Trajeto do ar no sistema respiratório', 'Fossas nasais → faringe → laringe → traqueia → brônquios → bronquíolos → alvéolos pulmonares.'),
  ('Biologia', 'Fisiologia Humana — Respiratório', 'Hematose', 'Troca gasosa que ocorre nos alvéolos pulmonares, na qual o O2 do ar difunde-se para o sangue e o CO2 do sangue difunde-se para o ar.'),
  ('Biologia', 'Fisiologia Humana — Respiratório', 'Local da produção de energia celular a partir do O2 inspirado', 'Nas mitocôndrias, durante a respiração celular, onde o oxigênio atua como aceptor final de elétrons na cadeia respiratória.'),
  ('Biologia', 'Fisiologia Humana — Respiratório', 'Hemoglobina — função no transporte de gases', 'Proteína presente nas hemácias que se liga reversivelmente ao O2 (oxi-hemoglobina) e transporta parte do CO2 e H+ produzidos no metabolismo.'),
  ('Biologia', 'Fisiologia Humana — Endócrino', 'Glândula endócrina — definição', 'Órgão que secreta hormônios diretamente na corrente sanguínea, sem ductos, para atuar em órgãos-alvo distantes.'),
  ('Biologia', 'Fisiologia Humana — Endócrino', 'Exemplos de glândulas endócrinas', 'Hipófise (pituitária), tireoide, paratireoides, adrenais (suprarrenais), pâncreas (porção endócrina), ovários e testículos.'),
  ('Biologia', 'Fisiologia Humana — Endócrino', 'Hipófise — papel funcional', 'Considerada a "glândula mestra"; regula outras glândulas endócrinas por meio de hormônios tróficos.'),
  ('Biologia', 'Fisiologia Humana — Endócrino', 'Insulina — função', 'Hormônio pancreático que reduz a glicemia, facilitando a entrada de glicose nas células e seu armazenamento como glicogênio.'),
  ('Biologia', 'Fisiologia Humana — Endócrino', 'Diabetes mellitus — mecanismo básico', 'Doença causada pela produção insuficiente de insulina ou pela resistência das células a ela, resultando em hiperglicemia.'),
  ('Biologia', 'Genética Mendeliana', '1ª Lei de Mendel (Lei da Segregação)', 'Cada característica é determinada por um par de fatores (alelos) que se separam durante a formação dos gametas, sendo cada gameta portador de apenas um alelo do par.'),
  ('Biologia', 'Genética Mendeliana', '2ª Lei de Mendel (Lei da Segregação Independente)', 'Genes localizados em cromossomos diferentes (ou distantes no mesmo cromossomo) segregam-se de forma independente durante a formação dos gametas.'),
  ('Biologia', 'Genética Mendeliana', 'Cruzamento-teste (test cross)', 'Cruzamento entre um indivíduo de fenótipo dominante com genótipo desconhecido e um indivíduo homozigoto recessivo, usado para determinar o genótipo do primeiro.'),
  ('Biologia', 'Genética Mendeliana', 'Herança autossômica recessiva — exemplo', 'Albinismo; o indivíduo afetado é homozigoto recessivo (aa), podendo ambos os pais serem heterozigotos (Aa) sem manifestar a condição.'),
  ('Biologia', 'Genética Mendeliana', 'Anemia falciforme — tipo de herança', 'Herança autossômica recessiva; o heterozigoto (HbAS) é portador assintomático (traço falciforme), enquanto o homozigoto recessivo (HbSS) manifesta a doença.'),
  ('Biologia', 'Genética Mendeliana', 'Fontes de variabilidade genética na meiose', 'Crossing-over (permutação gênica) e a segregação independente dos cromossomos homólogos na anáfase I.'),
  ('Biologia', 'Virologia', 'Vírus — características gerais', 'Partículas acelulares, parasitas intracelulares obrigatórios, compostos por material genético (DNA ou RNA) envolto por capsídeo proteico.'),
  ('Biologia', 'Virologia', 'Dengue — agente causador', 'Vírus da dengue (arbovírus), transmitido pela picada do mosquito Aedes aegypti fêmea infectado.'),
  ('Biologia', 'Virologia', 'Poliomielite — agente e principal característica', 'Causada pelo poliovírus, pode provocar paralisia flácida assimétrica e irreversível dos membros, principalmente inferiores.'),
  ('Biologia', 'Virologia', 'Mpox — classificação da doença', 'Zoonose viral, ou seja, transmitida de animais para humanos, podendo também haver transmissão entre pessoas por contato direto.'),
  ('Biologia', 'Microbiologia', 'Protozoários flagelados de importância médica', 'Giardia lamblia, Trypanosoma cruzi (agente da doença de Chagas) e Trichomonas vaginalis.'),
  ('Biologia', 'Microbiologia', 'Hanseníase — agente etiológico', 'Bactéria Mycobacterium leprae, transmitida por contato próximo e prolongado por vias aéreas superiores com doente não tratado.'),
  ('Biologia', 'Ecologia — Biomas', 'Bioma Amazônia — diversidade interna', 'Apresenta diferentes formações vegetais (matas de terra firme, várzea e igapó), variando conforme disponibilidade de água e altura da vegetação, mas ainda constituindo um único bioma.'),
  ('Biologia', 'Ecologia — Biomas', 'Bioma Cerrado — características gerais', 'Savana tropical brasileira com vegetação de troncos retorcidos, cascas grossas e raízes profundas, adaptada ao fogo e a solos ácidos.'),
  ('Biologia', 'Ecologia — Biomas', 'Pantanal — característica principal', 'Maior planície alagável do mundo, com alta biodiversidade aquática e terrestre, sujeita a ciclos de cheia e seca.'),
  ('Biologia', 'Ecologia — Biomas', 'Mata Atlântica — situação de conservação', 'Bioma com vegetação florestal densa e heterogênea, altamente fragmentado e ameaçado por séculos de ocupação urbana no litoral brasileiro.'),
  ('Biologia', 'Ecologia — Biomas', 'Pampa — características', 'Predomínio de vegetação campestre (gramíneas), clima subtropical com ocorrência de invernos rigorosos, restrito ao Rio Grande do Sul.'),
  ('Química', 'Funções Orgânicas', 'Função cetona', 'Composto orgânico com o grupo carbonila (C=O) ligado a dois carbonos (grupo carbonila entre carbonos da cadeia).'),
  ('Química', 'Funções Orgânicas', 'Função aldeído', 'Composto orgânico com o grupo carbonila ligado a pelo menos um átomo de hidrogênio, geralmente na extremidade da cadeia carbônica.'),
  ('Química', 'Funções Orgânicas', 'Função éter', 'Composto orgânico em que um átomo de oxigênio está ligado a dois radicais orgânicos (R–O–R'').'),
  ('Química', 'Funções Orgânicas', 'Função amina', 'Compostos orgânicos derivados da amônia (NH3), em que um ou mais hidrogênios são substituídos por radicais orgânicos.'),
  ('Química', 'Funções Orgânicas', 'Função amida', 'Composto orgânico caracterizado pelo grupo carbonila ligado a um átomo de nitrogênio (–CO–NH2 ou derivados).'),
  ('Química', 'Funções Orgânicas', 'Diferença entre amina aromática e amina alifática', 'Amina aromática tem o grupo amino ligado diretamente a um anel aromático; amina alifática está ligada a uma cadeia carbônica não aromática.'),
  ('Química', 'Polímeros', 'Polímero — definição', 'Macromolécula formada pela repetição de unidades estruturais menores (monômeros) unidas por ligações covalentes.'),
  ('Química', 'Polímeros', 'Polietileno — monômero de origem', 'Formado a partir da polimerização do eteno (etileno, CH2=CH2).'),
  ('Química', 'Ácidos e Bases', 'Teoria de Brønsted-Lowry — ácido', 'Espécie capaz de doar um próton (H+) em uma reação química.'),
  ('Química', 'Ácidos e Bases', 'Teoria de Brønsted-Lowry — base', 'Espécie capaz de receber um próton (H+) em uma reação química.'),
  ('Química', 'Ácidos e Bases', 'Par ácido-base conjugado', 'Duas espécies que se diferem pela presença ou ausência de um próton (H+); o ácido, ao doar H+, forma sua base conjugada.'),
  ('Química', 'Ácidos e Bases', 'Escala de pH', 'Escala logarítmica (pH = -log[H+]) que mede a acidez ou basicidade de uma solução; valores menores que 7 são ácidos, maiores que 7 são básicos, e 7 é neutro (a 25 °C).'),
  ('Química', 'Ácidos e Bases', 'Hidrólise salina básica', 'Ocorre quando o sal é formado por ácido fraco e base forte; a solução resultante apresenta caráter básico (pH > 7).'),
  ('Química', 'Química Ambiental', 'Monóxido de carbono (CO) — toxicidade', 'Gás incolor e inodoro que se liga à hemoglobina com maior afinidade que o O2, formando carboxi-hemoglobina e causando intoxicação.'),
  ('Química', 'Química Ambiental', 'Chuva ácida — principais responsáveis', 'Óxidos de enxofre (SOx) e óxidos de nitrogênio (NOx) liberados na queima de combustíveis fósseis, que reagem com a água da atmosfera formando ácidos.'),
  ('Química', 'Radioatividade', 'Resíduos radioativos hospitalares — manejo', 'Devem passar por segregação, identificação, armazenamento temporário e transporte adequados, seguindo normas da CNEN (Comissão Nacional de Energia Nuclear).'),
  ('Física', 'Eletromagnetismo', 'Campo magnético gerado por corrente em fio retilíneo', 'B = μ0·i/(2π·d), onde μ0 é a permeabilidade magnética do vácuo, i a corrente e d a distância ao fio.'),
  ('Física', 'Eletromagnetismo', 'Campo magnético no centro de uma espira circular', 'B = μ0·i/(2R), onde R é o raio da espira.'),
  ('Física', 'Eletromagnetismo', 'Força magnética sobre carga em movimento (Força de Lorentz)', 'F = |q|·v·B·sen(θ), onde θ é o ângulo entre a velocidade e o campo magnético.'),
  ('Física', 'Eletromagnetismo', 'Lei de Faraday-Neumann-Lenz (indução eletromagnética)', 'A força eletromotriz induzida em um circuito é proporcional à taxa de variação do fluxo magnético que o atravessa, com sinal oposto à variação (Lei de Lenz).'),
  ('Física', 'Ondulatória', 'Equação fundamental da ondulatória', 'v = λ·f, relaciona velocidade de propagação, comprimento de onda e frequência.'),
  ('Física', 'Ondulatória', 'Movimento Harmônico Simples (MHS) — período do sistema massa-mola', 'T = 2π·√(m/k), onde m é a massa e k a constante elástica da mola.'),
  ('Física', 'Física Moderna', 'Contração do comprimento (Relatividade Restrita)', 'L = L0·√(1 - v²/c²), onde L0 é o comprimento próprio e v a velocidade relativa ao observador.'),
  ('Física', 'Física Moderna', 'Efeito fotoelétrico — energia do fóton', 'E = h·f, onde h é a constante de Planck e f a frequência da radiação incidente.'),
  ('Matemática', 'Geometria Analítica', 'Distância entre dois pontos no plano cartesiano', 'd = √[(x2-x1)² + (y2-y1)²].'),
  ('Matemática', 'Geometria Analítica', 'Equação reduzida da circunferência', '(x - a)² + (y - b)² = r², onde (a,b) é o centro e r o raio.'),
  ('Matemática', 'Trigonometria', 'Relação fundamental da trigonometria', 'sen²(x) + cos²(x) = 1.'),
  ('Matemática', 'Trigonometria', 'Lei dos Cossenos', 'a² = b² + c² - 2bc·cos(A), usada para relacionar lados e ângulos de um triângulo qualquer.'),
  ('Matemática', 'Logaritmos', 'Definição de logaritmo', 'logb(x) = y ⇔ b^y = x, sendo b a base (b > 0, b ≠ 1) e x o logaritmando (x > 0).'),
  ('Matemática', 'Logaritmos', 'Propriedade do logaritmo do produto', 'log(a·b) = log(a) + log(b).'),
  ('Português', 'Figuras de Linguagem', 'Metáfora', 'Figura de linguagem que estabelece comparação implícita entre dois elementos, sem uso de conectivo comparativo.'),
  ('Português', 'Figuras de Linguagem', 'Prosopopeia (personificação)', 'Atribuição de características humanas a seres inanimados ou irracionais.'),
  ('Português', 'Figuras de Linguagem', 'Hipérbole', 'Figura de linguagem que consiste em exagero proposital para dar ênfase a uma ideia.'),
  ('Português', 'Classes Gramaticais', 'Conjunção subordinativa integrante', 'Introduz orações subordinadas substantivas, sem valor semântico próprio (ex.: "que", "se" em orações como "Sabemos que...").'),
  ('Português', 'Classes Gramaticais', 'Advérbio de intensidade', 'Modifica adjetivo, verbo ou outro advérbio, indicando grau (ex.: "muito", "bastante", "mais").'),
  ('Português', 'Sintaxe', 'Objeto indireto', 'Complemento verbal preposicionado, exigido por verbos transitivos indiretos.'),
  ('Português', 'Sintaxe', 'Agente da passiva', 'Termo que indica quem pratica a ação na voz passiva, geralmente introduzido pela preposição "por".'),
  ('Inglês', 'Comparativos e Superlativos', 'Superlativo absoluto sintético em inglês', 'Formado com "the most" + adjetivo (para adjetivos longos) ou sufixo "-est" (para adjetivos curtos).'),
  ('Inglês', 'Vocabulário', '"Skyrocketing" (significado)', 'Aumentar de forma rápida e significativa (ex.: preços disparando).'),
  ('Inglês', 'Expressões Idiomáticas', '"Like a fish out of water"', 'Expressão idiomática que significa sentir-se deslocado ou inadequado em determinada situação/ambiente.'),
  ('Espanhol', 'Artigos', 'Uso de artigo indefinido plural "unas/unos"', 'Usado antes de substantivos plurais para indicar quantidade indeterminada (ex.: "unas manzanas").'),
  ('Espanhol', 'Vocabulário', '"Aislados" (tradução)', 'Isolados.'),
  ('Espanhol', 'Advérbios', '"Muy" x "Mucho"', '"Muy" acompanha adjetivos e advérbios; "mucho" acompanha substantivos ou verbos.'),
  ('História', 'Brasil Colônia', 'Invasões holandesas no Nordeste', 'Ocupação holandesa da região açucareira de Pernambuco a partir de 1630, disputando com Portugal o controle da produção de açúcar.'),
  ('História', 'Idade Antiga', 'Reformas de Sólon em Atenas', 'Aboliu a escravidão por dívida, entre outras medidas que reduziram tensões sociais e prepararam o caminho para a democracia ateniense.'),
  ('História', 'Revolução Industrial', 'Ludismo', 'Movimento de trabalhadores do século XIX que destruía máquinas industriais em protesto contra a precarização do trabalho.'),
  ('História', 'Brasil República', 'Constituição de 1988 — marco', 'Restabeleceu a soberania popular no Brasil através do sufrágio universal, com voto direto e de igual valor para todos os eleitores.'),
  ('Geografia', 'Geografia Agrária', 'Lei de Terras de 1850 (Brasil)', 'Estabeleceu que o acesso à terra só poderia ocorrer por meio de compra, restringindo o acesso de camponeses pobres e populações recém-libertas, consolidando a estrutura latifundiária.'),
  ('Geografia', 'Geopolítica', 'Racismo ambiental', 'Conceito que descreve como grupos historicamente marginalizados são desproporcionalmente afetados por riscos ambientais e ocupação de áreas de risco.'),
  ('Geografia', 'Geografia Urbana', 'Gentrificação', 'Processo de valorização imobiliária de uma área urbana que provoca o deslocamento da população original de baixa renda.'),
  ('Biologia', 'Respiração Celular', 'Etapas da respiração celular aeróbica', 'Glicólise (citoplasma) → Ciclo de Krebs (matriz mitocondrial) → Cadeia transportadora de elétrons e fosforilação oxidativa (crista mitocondrial), produzindo cerca de 30-32 ATP por molécula de glicose.'),
  ('Biologia', 'Respiração Celular', 'Glicólise — produtos finais', 'A partir de 1 molécula de glicose (6C), produz 2 moléculas de piruvato, 2 ATP líquidos e 2 NADH, ocorrendo no citosol sem consumo de oxigênio.'),
  ('Biologia', 'Respiração Celular', 'Ciclo de Krebs — onde ocorre e o que produz', 'Ocorre na matriz mitocondrial; a partir do Acetil-CoA, gera CO2, NADH, FADH2 e uma pequena quantidade de ATP (via GTP) por volta completa.'),
  ('Biologia', 'Respiração Celular', 'Cadeia transportadora de elétrons — aceptor final', 'O oxigênio (O2) é o aceptor final de elétrons, combinando-se com H+ para formar água (H2O); é a etapa que gera a maior parte do ATP.'),
  ('Biologia', 'Embriologia', 'Sequência de eventos da fertilização e desenvolvimento embrionário', 'Ovulação e fecundação → formação do zigoto → clivagem e transporte → estágios de desenvolvimento (mórula, blastocisto) → nidação (implantação).'),
  ('Biologia', 'Embriologia', 'Clivagem embrionária', 'Sucessivas divisões mitóticas do zigoto sem aumento de volume total, formando a mórula e, posteriormente, o blastocisto.'),
  ('Biologia', 'Embriologia', 'Nidação', 'Processo de implantação do blastocisto na parede do endométrio uterino, geralmente cerca de uma semana após a fecundação.'),
  ('Biologia', 'Genética Avançada', 'Epistasia', 'Fenômeno em que um gene (epistático) interfere na expressão de outro gene (hipostático), que ocupa um locus diferente, mascarando ou modificando seu fenótipo.'),
  ('Biologia', 'Genética Avançada', 'Herança quantitativa (poligênica)', 'Característica determinada por dois ou mais pares de genes, cada um contribuindo aditivamente para o fenótipo, gerando variação contínua (ex.: cor da pele humana).'),
  ('Biologia', 'Genética Avançada', 'Pleiotropia', 'Fenômeno em que um único gene influencia múltiplas características fenotípicas aparentemente não relacionadas.'),
  ('Biologia', 'Imunologia', 'Imunidade inata x adaptativa', 'A imunidade inata é inespecífica e imediata (barreiras físicas, fagócitos); a adaptativa é específica, mais lenta na primeira resposta, mas gera memória imunológica (linfócitos B e T).'),
  ('Biologia', 'Imunologia', 'Anticorpos (imunoglobulinas) — função', 'Proteínas produzidas pelos linfócitos B (plasmócitos) que se ligam especificamente a antígenos, neutralizando-os ou marcando-os para destruição.'),
  ('Biologia', 'Histologia', 'Tecido epitelial — características gerais', 'Células justapostas, com pouca substância intercelular, avascular (nutrido por difusão) e com alta capacidade de renovação (mitoses frequentes).'),
  ('Biologia', 'Histologia', 'Tecido conjuntivo — características gerais', 'Rico em matriz extracelular e vascularizado, com grande diversidade de tipos celulares (fibroblastos, adipócitos) e funções (sustentação, preenchimento, defesa).'),
  ('Biologia', 'Fisiologia Renal', 'Néfron — unidade funcional do rim', 'Estrutura responsável pela filtração do sangue, reabsorção de substâncias úteis e secreção de substâncias, formando a urina.'),
  ('Química', 'Cinética Química', 'Fatores que aumentam a velocidade de uma reação', 'Aumento da temperatura, da concentração dos reagentes, da superfície de contato e uso de catalisadores.'),
  ('Química', 'Cinética Química', 'Catalisador — mecanismo de ação', 'Diminui a energia de ativação da reação, aumentando sua velocidade, sem ser consumido no processo e sem alterar a variação de entalpia (ΔH).'),
  ('Química', 'Cinética Química', 'Energia de ativação', 'Energia mínima necessária para que uma colisão entre reagentes resulte efetivamente em reação química.'),
  ('Química', 'Equilíbrio Iônico', 'Produto iônico da água (Kw)', 'Kw = [H+]·[OH-] = 10⁻¹⁴ a 25 °C, relação constante entre as concentrações de íons H+ e OH- em soluções aquosas.'),
  ('Química', 'Soluções', 'Solução tampão — como funciona', 'Mistura de um ácido fraco e sua base conjugada (ou vice-versa) que resiste a variações bruscas de pH quando pequenas quantidades de ácido ou base são adicionadas.'),
  ('Química', 'Estequiometria de Gases', 'Lei de Boyle (transformação isotérmica)', 'Para temperatura constante, a pressão e o volume de um gás são inversamente proporcionais (P1·V1 = P2·V2).'),
  ('Química', 'Estequiometria de Gases', 'Lei de Gay-Lussac (transformação isocórica)', 'Para volume constante, a pressão de um gás é diretamente proporcional à sua temperatura absoluta (P1/T1 = P2/T2).'),
  ('Química', 'Química Orgânica Avançada', 'Reação de identificação de aldeídos (Reagente de Tollens)', 'Aldeídos reduzem o íon Ag+ do reagente de Tollens a prata metálica (espelho de prata), enquanto cetonas não reagem, sendo um teste diferencial entre as duas funções.'),
  ('Química', 'Química Orgânica Avançada', 'Hidrogenação de alcenos', 'Reação de adição em que H2 é incorporado à dupla ligação C=C na presença de catalisador metálico (Ni, Pt ou Pd), formando um alcano.'),
  ('Química', 'Bioquímica', 'Proteínas — ligação entre aminoácidos', 'Ligação peptídica, formada entre o grupo carboxila de um aminoácido e o grupo amina de outro, com liberação de água (reação de condensação).'),
  ('Química', 'Bioquímica', 'Estrutura primária de uma proteína', 'Sequência linear de aminoácidos unidos por ligações peptídicas, determinada geneticamente.'),
  ('Física', 'Gravitação', 'Lei da Gravitação Universal de Newton', 'F = G·(m1·m2)/d², onde G é a constante gravitacional, m1 e m2 as massas dos corpos e d a distância entre seus centros.'),
  ('Física', 'Gravitação', 'Velocidade orbital mínima (órbita circular rasante)', 'Ocorre quando a força gravitacional fornece exatamente a força centrípeta necessária à órbita, definindo v = √(g·R), onde R é o raio da órbita.'),
  ('Física', 'Termodinâmica', 'Primeira Lei da Termodinâmica', 'ΔU = Q - W, a variação da energia interna de um sistema é igual ao calor trocado menos o trabalho realizado pelo sistema.'),
  ('Física', 'Termodinâmica', 'Diagrama de mudança de fase — patamar de temperatura constante', 'Durante uma mudança de estado físico (fusão, vaporização), a temperatura permanece constante enquanto o calor latente é fornecido ou retirado.'),
  ('Física', 'Hidrostática', 'Princípio de Stevin (pressão hidrostática)', 'P = P0 + ρ·g·h, a pressão em um ponto de um fluido em repouso depende da pressão na superfície, da densidade do fluido, da gravidade e da profundidade.'),
  ('Física', 'Mecânica', 'Torque (momento de uma força)', 'τ = F·d·sen(θ), onde d é a distância do ponto de aplicação da força ao eixo de rotação, e θ o ângulo entre a força e o braço de alavanca.'),
  ('Física', 'Mecânica', 'Condição de equilíbrio de um corpo rígido', 'A soma vetorial das forças deve ser nula e a soma dos torques (momentos) em relação a qualquer ponto também deve ser nula.'),
  ('Física', 'Eletrodinâmica', 'Potência elétrica dissipada em um resistor', 'P = U·i = R·i² = U²/R, relaciona potência, tensão, corrente e resistência.'),
  ('Matemática', 'Geometria Espacial', 'Volume do cone', 'V = (1/3)·π·r²·h, onde r é o raio da base e h a altura do cone.'),
  ('Matemática', 'Geometria Espacial', 'Área total do cubo', 'A = 6·a², onde a é a medida da aresta do cubo.'),
  ('Matemática', 'Probabilidade Condicional', 'Fórmula da probabilidade condicional', 'P(A|B) = P(A ∩ B)/P(B), probabilidade de ocorrer A dado que B já ocorreu.'),
  ('Matemática', 'Estatística', 'Mediana de um conjunto de dados', 'Valor central de um conjunto ordenado de dados; se o número de elementos for par, é a média aritmética dos dois valores centrais.'),
  ('Matemática', 'Estatística', 'Média ponderada', 'Soma dos produtos de cada valor pelo seu respectivo peso, dividida pela soma dos pesos.'),
  ('História', 'Revolução Francesa', 'Principais causas da Revolução Francesa de 1789', 'Crise financeira do Estado, desigualdade entre os três estamentos (clero, nobreza e terceiro estado) e difusão dos ideais iluministas.'),
  ('História', 'Era Vargas', 'Getúlio Vargas — política econômica de industrialização', 'Promoveu a criação de empresas estatais estratégicas, como a base para o que depois seria a Petrobras, fortalecendo a indústria de base nacional.'),
  ('História', 'Segunda Guerra Mundial', 'Consequência geopolítica imediata da Segunda Guerra Mundial', 'Ascensão de EUA e URSS como superpotências e início da bipolarização do mundo, dando origem à Guerra Fria.'),
  ('Geografia', 'Climatologia', 'Efeito da altitude sobre a pressão e temperatura atmosférica', 'Quanto maior a altitude, menor a pressão atmosférica (menor coluna de ar) e, em geral, menor a temperatura, devido à menor densidade do ar.'),
  ('Geografia', 'Geopolítica Ambiental', 'COP (Conferência das Partes) — função', 'Órgão decisório da Convenção-Quadro das Nações Unidas sobre Mudança do Clima, responsável por implementar compromissos globais de combate às mudanças climáticas.'),
  ('Geografia', 'Placas Tectônicas', 'Limite transformante de placas', 'Região onde as placas tectônicas deslizam lateralmente uma em relação à outra, sem criação ou destruição de crosta, mas com ocorrência de tremores de terra (ex.: Falha de San Andreas).'),
  ('Geografia', 'Geografia da População', 'Desertificação — definição', 'Processo de degradação do solo em áreas áridas, semiáridas e subúmidas secas, resultante de fatores climáticos e de atividades humanas inadequadas (desmatamento, monocultura).');
